/**
 * Chart Generator — Converts chart specs to SVG buffer
 *
 * Server-side chart rendering using SVG string generation.
 * No external binary or canvas dependencies needed.
 */

interface DatasetData {
    label: string;
    data: string[];   // Numeric values as strings
    color: string;
}

interface ChartData {
    title: string;
    chartType: string;  // 'bar' | 'line' | 'pie' | 'horizontal_bar'
    labels: string[];
    datasets: DatasetData[];
    summary: string;
}

const DEFAULT_COLORS = ['#16C79A', '#E94560', '#5C7AEA', '#F5A623', '#7C3AED', '#EC4899', '#14B8A6', '#F97316'];

/**
 * Generate a chart as SVG buffer.
 */
export function generateChart(data: ChartData): Buffer {
    const width = 800;
    const height = 500;
    const padding = { top: 60, right: 40, bottom: 80, left: 60 };
    const chartW = width - padding.left - padding.right;
    const chartH = height - padding.top - padding.bottom;

    // Parse numeric values
    const parsedDatasets = data.datasets.map((ds, i) => ({
        label: ds.label,
        values: ds.data.map(v => parseFloat(v) || 0),
        color: ds.color || DEFAULT_COLORS[i % DEFAULT_COLORS.length],
    }));

    const allValues = parsedDatasets.flatMap(ds => ds.values);
    const maxVal = Math.max(...allValues, 1);
    const minVal = Math.min(0, ...allValues);
    const range = maxVal - minVal;

    let chartContent = '';
    const type = data.chartType.toLowerCase();

    if (type === 'bar' || type === 'horizontal_bar') {
        chartContent = renderBarChart(data.labels, parsedDatasets, chartW, chartH, maxVal, range, padding);
    } else if (type === 'line') {
        chartContent = renderLineChart(data.labels, parsedDatasets, chartW, chartH, maxVal, range, padding);
    } else if (type === 'pie') {
        chartContent = renderPieChart(data.labels, parsedDatasets, width, height);
    } else {
        chartContent = renderBarChart(data.labels, parsedDatasets, chartW, chartH, maxVal, range, padding);
    }

    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <rect width="${width}" height="${height}" fill="#1A1A2E" rx="12"/>
  <text x="${width / 2}" y="35" text-anchor="middle" font-family="Segoe UI, sans-serif" font-size="18" font-weight="bold" fill="#FFFFFF">${escapeXml(data.title)}</text>
  ${chartContent}
  <text x="${width / 2}" y="${height - 10}" text-anchor="middle" font-family="Segoe UI, sans-serif" font-size="10" fill="#64748B">Generated by Nousio</text>
</svg>`;

    return Buffer.from(svg, 'utf-8');
}

function renderBarChart(
    labels: string[],
    datasets: { label: string; values: number[]; color: string }[],
    chartW: number, chartH: number, maxVal: number, range: number,
    padding: { top: number; right: number; bottom: number; left: number },
): string {
    const groupCount = labels.length;
    const barGroupWidth = chartW / groupCount;
    const barWidth = Math.min(barGroupWidth * 0.6 / datasets.length, 40);
    let bars = '';

    // Y-axis gridlines
    for (let i = 0; i <= 4; i++) {
        const y = padding.top + (chartH * i / 4);
        const val = Math.round(maxVal - (range * i / 4));
        bars += `<line x1="${padding.left}" y1="${y}" x2="${padding.left + chartW}" y2="${y}" stroke="#334155" stroke-width="0.5"/>`;
        bars += `<text x="${padding.left - 8}" y="${y + 4}" text-anchor="end" font-family="Segoe UI" font-size="10" fill="#94A3B8">${val}</text>`;
    }

    // Bars
    for (let gi = 0; gi < groupCount; gi++) {
        const groupX = padding.left + gi * barGroupWidth + barGroupWidth * 0.2;

        for (let di = 0; di < datasets.length; di++) {
            const val = datasets[di].values[gi] || 0;
            const barH = (val / maxVal) * chartH;
            const x = groupX + di * barWidth;
            const y = padding.top + chartH - barH;
            bars += `<rect x="${x}" y="${y}" width="${barWidth - 2}" height="${barH}" fill="${datasets[di].color}" rx="3" opacity="0.9"/>`;
        }

        // Label
        const labelX = padding.left + gi * barGroupWidth + barGroupWidth / 2;
        bars += `<text x="${labelX}" y="${padding.top + chartH + 20}" text-anchor="middle" font-family="Segoe UI" font-size="10" fill="#94A3B8">${escapeXml(labels[gi]?.substring(0, 12) || '')}</text>`;
    }

    // Legend
    let legendX = padding.left;
    for (const ds of datasets) {
        bars += `<rect x="${legendX}" y="${padding.top + chartH + 45}" width="12" height="12" fill="${ds.color}" rx="2"/>`;
        bars += `<text x="${legendX + 16}" y="${padding.top + chartH + 56}" font-family="Segoe UI" font-size="10" fill="#CBD5E1">${escapeXml(ds.label)}</text>`;
        legendX += ds.label.length * 7 + 30;
    }

    return bars;
}

function renderLineChart(
    labels: string[],
    datasets: { label: string; values: number[]; color: string }[],
    chartW: number, chartH: number, maxVal: number, range: number,
    padding: { top: number; right: number; bottom: number; left: number },
): string {
    const pointSpacing = chartW / Math.max(labels.length - 1, 1);
    let lines = '';

    // Y gridlines
    for (let i = 0; i <= 4; i++) {
        const y = padding.top + (chartH * i / 4);
        const val = Math.round(maxVal - (range * i / 4));
        lines += `<line x1="${padding.left}" y1="${y}" x2="${padding.left + chartW}" y2="${y}" stroke="#334155" stroke-width="0.5"/>`;
        lines += `<text x="${padding.left - 8}" y="${y + 4}" text-anchor="end" font-family="Segoe UI" font-size="10" fill="#94A3B8">${val}</text>`;
    }

    for (const ds of datasets) {
        const points = ds.values.map((val, i) => {
            const x = padding.left + i * pointSpacing;
            const y = padding.top + chartH - (val / maxVal) * chartH;
            return `${x},${y}`;
        });

        lines += `<polyline fill="none" stroke="${ds.color}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" points="${points.join(' ')}"/>`;

        // Dots
        for (const pt of points) {
            const [cx, cy] = pt.split(',');
            lines += `<circle cx="${cx}" cy="${cy}" r="4" fill="${ds.color}" stroke="#1A1A2E" stroke-width="2"/>`;
        }
    }

    // X labels
    for (let i = 0; i < labels.length; i++) {
        const x = padding.left + i * pointSpacing;
        lines += `<text x="${x}" y="${padding.top + chartH + 20}" text-anchor="middle" font-family="Segoe UI" font-size="10" fill="#94A3B8">${escapeXml(labels[i]?.substring(0, 12) || '')}</text>`;
    }

    return lines;
}

function renderPieChart(
    labels: string[],
    datasets: { label: string; values: number[]; color: string }[],
    width: number, height: number,
): string {
    const values = datasets[0]?.values || [];
    const total = values.reduce((a, b) => a + b, 0) || 1;
    const cx = width / 2 - 80;
    const cy = height / 2 + 10;
    const r = 140;
    let pie = '';
    let startAngle = -Math.PI / 2;

    for (let i = 0; i < values.length; i++) {
        const angle = (values[i] / total) * 2 * Math.PI;
        const endAngle = startAngle + angle;
        const largeArc = angle > Math.PI ? 1 : 0;
        const x1 = cx + r * Math.cos(startAngle);
        const y1 = cy + r * Math.sin(startAngle);
        const x2 = cx + r * Math.cos(endAngle);
        const y2 = cy + r * Math.sin(endAngle);
        const color = DEFAULT_COLORS[i % DEFAULT_COLORS.length];

        pie += `<path d="M${cx},${cy} L${x1},${y1} A${r},${r} 0 ${largeArc} 1 ${x2},${y2} Z" fill="${color}" stroke="#1A1A2E" stroke-width="2"/>`;
        startAngle = endAngle;
    }

    // Legend
    let ly = 80;
    for (let i = 0; i < Math.min(values.length, labels.length); i++) {
        const color = DEFAULT_COLORS[i % DEFAULT_COLORS.length];
        const pct = Math.round((values[i] / total) * 100);
        pie += `<rect x="${width - 170}" y="${ly}" width="12" height="12" fill="${color}" rx="2"/>`;
        pie += `<text x="${width - 152}" y="${ly + 11}" font-family="Segoe UI" font-size="11" fill="#CBD5E1">${escapeXml(labels[i]?.substring(0, 15) || '')} (${pct}%)</text>`;
        ly += 22;
    }

    return pie;
}

function escapeXml(str: string): string {
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
