/**
 * DOCX Generator — Converts structured document data to .docx buffer
 */

import {
    Document,
    Packer,
    Paragraph,
    TextRun,
    HeadingLevel,
    AlignmentType,
    Footer,
    PageNumber,
    NumberFormat,
} from 'docx';

interface SectionData {
    heading: string;
    content: string;
    level: string;  // '1' | '2' | '3'
}

interface DocumentData {
    title: string;
    sections: SectionData[];
    summary: string;
}

// Map level string to HeadingLevel
function getHeadingLevel(level: string): typeof HeadingLevel[keyof typeof HeadingLevel] {
    switch (level) {
        case '1': return HeadingLevel.HEADING_1;
        case '2': return HeadingLevel.HEADING_2;
        case '3': return HeadingLevel.HEADING_3;
        default: return HeadingLevel.HEADING_2;
    }
}

/**
 * Generate a DOCX file buffer from structured document data.
 */
export async function generateDocx(data: DocumentData): Promise<Buffer> {
    const children: Paragraph[] = [];

    // Title
    children.push(
        new Paragraph({
            children: [
                new TextRun({
                    text: data.title,
                    bold: true,
                    size: 56,  // 28pt in half-points
                    font: 'Segoe UI',
                    color: '1A1A2E',
                }),
            ],
            alignment: AlignmentType.LEFT,
            spacing: { after: 400 },
        })
    );

    // Horizontal line
    children.push(
        new Paragraph({
            border: {
                bottom: { color: '16C79A', space: 1, style: 'single', size: 6 },
            },
            spacing: { after: 300 },
        })
    );

    // Sections
    for (const section of data.sections) {
        // Section heading
        children.push(
            new Paragraph({
                text: section.heading,
                heading: getHeadingLevel(section.level),
                spacing: { before: 240, after: 120 },
            })
        );

        // Section content — split by paragraphs
        const paragraphs = section.content.split('\n').filter(p => p.trim());
        for (const para of paragraphs) {
            // Check if it's a bullet point
            const isBullet = /^[-•*]\s/.test(para);
            const cleanText = isBullet ? para.replace(/^[-•*]\s*/, '') : para;

            children.push(
                new Paragraph({
                    children: [
                        new TextRun({
                            text: cleanText,
                            size: 24,  // 12pt
                            font: 'Segoe UI',
                        }),
                    ],
                    bullet: isBullet ? { level: 0 } : undefined,
                    spacing: { after: isBullet ? 60 : 160 },
                })
            );
        }
    }

    // Summary section
    if (data.summary) {
        children.push(
            new Paragraph({
                text: 'Summary',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 120 },
            })
        );
        children.push(
            new Paragraph({
                children: [
                    new TextRun({
                        text: data.summary,
                        size: 24,
                        font: 'Segoe UI',
                        italics: true,
                        color: '64748B',
                    }),
                ],
                spacing: { after: 200 },
            })
        );
    }

    const doc = new Document({
        creator: 'Nousio',
        title: data.title,
        description: data.summary,
        sections: [
            {
                properties: {
                    page: {
                        margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
                        pageNumbers: { start: 1, formatType: NumberFormat.DECIMAL },
                    },
                },
                footers: {
                    default: new Footer({
                        children: [
                            new Paragraph({
                                alignment: AlignmentType.RIGHT,
                                children: [
                                    new TextRun({ text: 'Generated by Nousio — Page ', size: 16, color: '94A3B8' }),
                                    new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '94A3B8' }),
                                ],
                            }),
                        ],
                    }),
                },
                children,
            },
        ],
    });

    const buffer = await Packer.toBuffer(doc);
    return Buffer.from(buffer);
}
