/**
 * PPTX Generator — Converts structured slide data to .pptx buffer
 */

import PptxGenJS from 'pptxgenjs';

interface SlideData {
    title: string;
    content: string;
    notes: string;
    layout: string;  // 'title' | 'content' | 'two_column' | 'blank'
}

interface PresentationData {
    title: string;
    subtitle: string;
    slides: SlideData[];
    summary: string;
}

/**
 * Generate a PPTX file buffer from structured presentation data.
 */
export async function generatePptx(data: PresentationData): Promise<Buffer> {
    const pptx = new PptxGenJS();
    pptx.title = data.title;
    pptx.subject = data.subtitle;
    pptx.author = 'Nousio';
    pptx.layout = 'LAYOUT_WIDE';

    // Define theme colors
    const COLORS = {
        bg: '1A1A2E',
        text: 'FFFFFF',
        accent: '16C79A',
        muted: '94A3B8',
        card: '232342',
    };

    // Title slide
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: COLORS.bg };
    titleSlide.addText(data.title, {
        x: 0.8, y: 1.8, w: '85%', h: 1.2,
        fontSize: 36, bold: true, color: COLORS.text,
        fontFace: 'Segoe UI',
        align: 'left',
    });
    titleSlide.addText(data.subtitle, {
        x: 0.8, y: 3.2, w: '85%', h: 0.6,
        fontSize: 18, color: COLORS.muted,
        fontFace: 'Segoe UI',
        align: 'left',
    });
    titleSlide.addText('Generated by Nousio', {
        x: 0.8, y: 6.5, w: '50%', h: 0.4,
        fontSize: 10, color: COLORS.muted,
        fontFace: 'Segoe UI',
    });

    // Content slides
    for (const slideData of data.slides) {
        const slide = pptx.addSlide();
        slide.background = { color: COLORS.bg };

        // Slide title
        slide.addText(slideData.title, {
            x: 0.8, y: 0.4, w: '85%', h: 0.8,
            fontSize: 28, bold: true, color: COLORS.text,
            fontFace: 'Segoe UI',
            align: 'left',
        });

        // Accent bar under title
        slide.addShape(pptx.ShapeType.rect, {
            x: 0.8, y: 1.15, w: 1.5, h: 0.04,
            fill: { color: COLORS.accent },
        });

        // Content (formatted as bullet points if multiline)
        const contentLines = slideData.content.split('\n').filter(l => l.trim());
        const contentBody = contentLines.map(line => ({
            text: line.replace(/^[-•*]\s*/, ''),
            options: {
                fontSize: 16,
                color: COLORS.text,
                fontFace: 'Segoe UI',
                bullet: contentLines.length > 1 ? { type: 'number' as const } : undefined,
                paraSpaceAfter: 8,
            },
        }));

        slide.addText(contentBody, {
            x: 0.8, y: 1.5, w: '85%', h: 4.5,
            valign: 'top',
        });

        // Speaker notes
        if (slideData.notes) {
            slide.addNotes(slideData.notes);
        }
    }

    // Summary slide
    const summarySlide = pptx.addSlide();
    summarySlide.background = { color: COLORS.bg };
    summarySlide.addText('Summary', {
        x: 0.8, y: 0.4, w: '85%', h: 0.8,
        fontSize: 28, bold: true, color: COLORS.text,
        fontFace: 'Segoe UI',
    });
    summarySlide.addText(data.summary, {
        x: 0.8, y: 1.5, w: '85%', h: 4.5,
        fontSize: 16, color: COLORS.muted,
        fontFace: 'Segoe UI',
        valign: 'top',
    });

    // Generate buffer
    const arrayBuffer = await pptx.write({ outputType: 'arraybuffer' }) as ArrayBuffer;
    return Buffer.from(arrayBuffer);
}
